id: ADDFDDFFD
title: 'Chapter 1: Upodghātaḥ'
type: translation
source_metadata:
  languages:
  - zh
  - bo
  - sa
  - en
  datatype: PlainText
  created_at: 2022-03-01 23:38:46.829048
  last_modified_at: 2022-03-01 23:38:46.829053
