id: ADDFDDFFD
title: 'Chapter 3: Nirupamastavaḥ'
type: translation
source_metadata:
  languages:
  - zh
  - bo
  - sa
  - en
  datatype: PlainText
  created_at: 2022-03-01 23:38:46.854347
  last_modified_at: 2022-03-01 23:38:46.854358
