id: ADDFDDFFD
title: 'Chapter 5: Rūpastavaḥ'
type: translation
source_metadata:
  languages:
  - zh
  - bo
  - sa
  - en
  datatype: PlainText
  created_at: 2022-03-01 23:38:46.863309
  last_modified_at: 2022-03-01 23:38:46.863312
